config/routes.rb
Mylittleyacht::Application.routes.draw do
  

  resources :yachts

  devise_for :users, :controllers => { :registrations => :registrations }

  get '/terms' => 'pages#page', page: "terms", as: "terms"
  get '/about' => 'pages#page', page: "about", as: "about"
  get '/join' => 'pages#page', page: "join_us", as: "join_us"

  resources :users, only: :show

  root :to => "pages#page", page: "home"

end

app/models/bookings.rb
class Bookings < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base

	belongs_to :yacht

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :yachts, foreign_key: :skipper_id

end

app/models/yacht.rb
class Yacht < ActiveRecord::Base
	belongs_to :skipper, class_name: 'User'

	has_many :pictures, dependent: :destroy
	accepts_nested_attributes_for :pictures
	validates :name, :title, :cabins_number, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:page]
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name  << :last_name  << :telephone
    devise_parameter_sanitizer.for(:account_update) << :first_name  << :last_name  << :telephone
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def page
  	render params[:page]
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	protected
  def after_update_path_for(resource)
  	user_path(resource)
  end

   def after_sign_up_path_for(resource)
    new_yacht_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		 @user = User.find(params[:id])
	end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  before_action :set_yacht, only: [:show, :edit, :update, :destroy]

  # GET /yachts
  # GET /yachts.json
  def index
    @yachts = Yacht.all
  end

  # GET /yachts/1
  # GET /yachts/1.json
  def show
  end

  # GET /yachts/new
  def new
    @yacht = Yacht.new
    @picture = @yacht.pictures.build
  end

  # GET /yachts/1/edit
  def edit
    @picture = @yacht.pictures.build
  end

  # POST /yachts
  # POST /yachts.json
  def create
    @yacht = current_user.yachts.build(yacht_params)

    respond_to do |format|
      if @yacht.save
        format.html { redirect_to @yacht, notice: 'Yacht was successfully created.' }
        format.json { render action: 'show', status: :created, location: @yacht }
      else
        format.html { render action: 'new' }
        format.json { render json: @yacht.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yachts/1
  # PATCH/PUT /yachts/1.json
  def update
    respond_to do |format|
      if @yacht.update(yacht_params)
        format.html { redirect_to @yacht, notice: 'Yacht was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @yacht.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yachts/1
  # DELETE /yachts/1.json
  def destroy
    @yacht.destroy
    respond_to do |format|
      format.html { redirect_to yachts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yacht
      @yacht = Yacht.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yacht_params
      params.require(:yacht).permit(:skipper_id, :name, :title, :description, :type, :length, :harbor, :year, :guests_number, :crew_number, :cabins_number, pictures_attributes: [:id, :photo])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yachts_helper.rb
module YachtsHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<ul>
		<li><%= link_to "Terms", terms_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Join us on Twitter", join_us_path %></li>
	</ul
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag "logo.jpg", alt: "Logo_My_Little_Yacht"%></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
        <li>
          <%= link_to new_yacht_path, class: "btn btn-warning" do %>
            <span class="glyphicon glyphicon-plus"></span> Add a Yacht
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyLittleYacht</title>
  <%= stylesheet_link_tag   "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="background-home">
	<%= render 'layouts/navbar' %>
  <p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
</div>

<div>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<div class="row">
  <div class="col-xs-6 col-md-3">
      <%= image_tag ("matbernard.jpg") %>
  </div>
  
</div>

app/views/pages/home.html.erb
<div id="banner">
	<header>
		<p class="text-jumbo"> Find a yacht to cruise </p>
		<p class="baseline"> Rent at best price directly from skippers. With friends or Family. </p>
		<button type="submit" class="btn-lg btn-info"><span class="glyphicon glyphicon-search"></span><%= link_to " Search", yachts_path %></button>
	</header>

</div>

app/views/pages/join_us.html.erb
<h1><a href="https://twitter.com/BeMyBoat">Join Us on Twitter</a></h1>

<p>We think that it is really important to develop our skippers' network. 
</p>
<p>If you would like to follow our acivity on real-time, we advise you to follow us on twitter. </p>

<a class="btn btn-primary btn-lg" data-toggle="modal" data-target="#ma-modale">
  Launch demo modal
</a>

<div class="modal fade" id="ma-modale">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/show.html.erb
  <div>
		<h2><%= @user.first_name %></h2>
		<h2><%= @user.last_name %></h2>
    <h2><%= @user.email %><br></h2>
    <h2><%= @user.telephone %><br></h2>

    <h2> My yachts for rental baby! </h2>
    <% @user.yachts.each do |y| %>
    <h3><%= link_to y.name, yacht_path(y) %></h3>
    <% end %>

		<% if current_user == @user %>
		 <button type="submit" class="btn btn-success"><%= link_to "Edit", edit_user_registration_path %></button>
		<% end %>

  </div>

app/views/yachts/_form.html.erb
<%= form_for(@yacht) do |f| %>
  <% if @yacht.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yacht.errors.count, "error") %> prohibited this yacht from being saved:</h2>

      <ul>
      <% @yacht.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, placeholder: "Your yacht in a one-line description", class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :type %><br>
        <%= f.text_field :type, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :length %><br>
        <%= f.text_field :length, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :harbor %><br>
        <%= f.text_area :harbor, class: "form-control" %>
      </div>
    </div>
  </div>

   <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :year %><br>
        <%= f.text_field :year, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :guests_number %><br>
        <%= f.text_field :guests_number, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :crew_number %><br>
        <%= f.text_area :crew_number, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :cabins_number %><br>
        <%= f.text_field :cabins_number, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.fields_for :pictures, @picture do |picture_form| %>
          <%= picture_form.file_field :photo %>
        <% end %>
      </div>
    </div>  
  </div>

  <button type="submit" class="btn btn-success">Add your beautiful Little Yacht</button>
<% end %>

app/views/yachts/edit.html.erb
<h1>Editing yacht</h1>

<%= render 'form' %>

<%= link_to 'Show', @yacht %> |
<%= link_to 'Back', yachts_path %>

app/views/yachts/index.html.erb
<h1>Listing yachts</h1>

<table>
  <thead>
    <tr>
      <th>Skipper</th>
      <th>Name</th>
      <th>Length</th>
      <th>Harbor</th>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @yachts.each do |yacht| %>
      <tr>
        <td><h3><%= yacht.skipper_id %></h3></td>
        <td><h3><%= yacht.name %></h3></td>
        <td><h3><%= yacht.length %></h3></td>
        <td><h3><%= yacht.harbor %></h3></td>
        <td><h3><%= yacht.year %></h3></td>
        <td><%= link_to 'Show', yacht %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yacht', new_yacht_path %>

app/views/yachts/new.html.erb
<h1>New yacht</h1>

<%= render 'form' %>

<%= link_to 'Back', yachts_path %>

app/views/yachts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yacht.name %>
</p>

<p>
  <strong>Length:</strong>
  <%= @yacht.length %>
</p>

<p>
  <strong>Harbor:</strong>
  <%= @yacht.harbor %>
</p>

<p>
  <strong>Year:</strong>
  <%= @yacht.year %>
</p>

<p>
  <strong>Cabins number:</strong>
  <%= @yacht.cabins_number %>
</p>

<p>
  <strong>Photos:</strong><br>
  <% @yacht.pictures.each do |pict| %>
    <li style="list-style-type: none"><%= image_tag pict.photo.url(:medium) %></li>
  <% end %>
</p>

<%= link_to 'Back', yachts_path %>
<% if current_user == @yacht.skipper %> |
    <%= link_to 'Edit', edit_yacht_path(@yacht) %> |
    <%= link_to 'Destroy', @yacht, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>